# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_stuff',
            name='image',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
