# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_used_stuff_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_stuff',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 14, 15, 44, 39, 985089, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
