# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_used_stuff_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='used_stuff',
            name='purchased_price',
        ),
    ]
